# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 4eyes_poc
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 4eyesP@ssw0rd
    volumes:
      - ./db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080